### ISSUE TITLE
Does not build on Rust 1.76.0+ due to rustc-serialize dependency

### ISSUE THREAD

**Issue by wezm** [guoxbin/dtool#38]
```
rustc-serialize v0.3.24
└── rust-crypto v0.2.36
    └── dtool v0.12.0 (/home/wmoore/Source/github.com/guoxbin/dtool)
```

```
error[E0310]: the parameter type `T` may not live long enough
    --> /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-serialize-0.3.24/src/serialize.rs:1155:5
     |
1155 |     fn decode<D: Decoder>(d: &mut D) -> Result<Cow<'static, T>, D::Error> {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |     |
     |     the parameter type `T` must be valid for the static lifetime...
     |     ...so that the type `T` will meet its required lifetime bounds...
     |
note: ...that is required by this bound
    --> /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/borrow.rs:180:30
help: consider adding an explicit lifetime bound
     |
1151 | impl<'a, T: ?Sized + 'static> Decodable for Cow<'a, T>
     |                    +++++++++
```

It looks like the `rust-crypto` crate is unmaintained, so there is no newer version that does not depend on the deprecated `rustc-serialize` crate. An alternative crate would need to be selected.

**Comment by guoxbin** [comment]
solved in v0.13.0
